# [√]需要手动修改 [-]不推荐修改 [※]可选项，不影响系统运行
# ===================================================
# [√] Redis 节点连接配置
# ---------------------------------------------------
# Tips：使用脚手架检测连接 python main.py ping
# ===================================================
REDIS_NODE:
  host: "127.0.0.1"
  password: ""
  port: 6379
  db: 0

# ===================================================
# [√] 订阅池容量
# ---------------------------------------------------
# POOL_CAP 为订阅池容量，用于限制采集器的行为
# ---------------------------------------------------
# Tips: POOL_CAP >= 80% 不再添加新任务
# Tips: POOL_CAP >= 50% 开始优选待办任务
# Tips: POOL_CAP >= 0% 灌入数据集
# Tips: 个人使用推荐 POOL_CAP∈[5,8]
# ---------------------------------------------------
# Warning: POOL_CAP不能超过30，这会带来极大的性能开支
# ===================================================
POOL_CAP: 8

# ===================================================
# [-] 定时任务配置
# ---------------------------------------------------
# collector     |采集器
# decoupler      |订阅池检测（heartbeat），清洗无效订阅
# ---------------------------------------------------
# interval      |任务间隔，单位秒
# Default: interval--(collector)--120s
# Default: interval--(decouple)--600s
# ---------------------------------------------------
# Tips: 手动修改的 interval 不可小于默认值
# ===================================================
scheduler:
  collector:
    enable: true
    interval: 120
  decoupler:
    enable: true
    interval: 600

# ===================================================
# [-※] 订阅池服务监控接口
# ---------------------------------------------------
# name       |微服务注册表名称，保持默认即可。
# uuid       |穿插在router-path中的随机字符串，默认为空。
#             建议手动指定，否则每次启动项目uuid都会随机生成
# host       |老规矩，根据需要切换到 ``0.0.0.0``
# apis       |开放使用的订阅池监控接口模板，不建议修改。
# ===================================================
router:
  name: "V2RSS"
  host: "127.0.0.1"
  port: 22333
  apis:
    # GET 快速获取 v2ray 订阅链接
    get_v2ray: "/api/v2rss/get/v2ray"
    # POST 快速获取某个类型的订阅链接
    get_subs_v1: "/api/v2rss/get_subs/v1"
    # POST 通过传入域名缩写进行模糊匹配，返回返回指定订阅源链接
    get_subs_v2: "/api/v2rss/get_subs/v2"
    # GET 获取池中来自不同订阅源的链接剩余数
    get_pool_status: "/api/v2rss/status"
